import { createContext } from 'react';

export const TestimonialContext = createContext({
  testimonials: [
    {
      id: 1,
      name: 'Viezh Robert',
      location: 'Warsaw, Poland',
      image: './images/user1.png',
      rating: '4.5',
      text: '“Wow... I am very happy to use this VPN, it turned out to be more than my expectations and so far there have been no problems. LaslesVPN always the best”.',
      isRed: true,
    },
    {
      id: 2,
      name: 'Yessica Christy',
      location: 'Shanxi, China',
      image: './images/user2.png',
      rating: '4.7',
      text: '“I like it because I like to travel far and still can connect with high speed.”.',
      isRed: false,
    },
    {
      id: 3,
      name: 'Kim Young Jou',
      location: 'Seoul, South Korea',
      image: './images/user3.png',
      rating: '4.5',
      text: '“This is very unusual for my business that currently requires a virtual private network that has high security.”.',
      isRed: false,
    },
    {
      id: 4,
      name: 'Maxim Hutsuliak',
      location: 'Chernivtsi, Ukraine',
      image: './images/user-placeholder.png',
      rating: '5',
      text: '“Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur iusto tempore deleniti, ad quaerat sapiente, a, adipisci sint nostrum ducimus earum. Consectetur voluptates soluta fuga, dignissimos molestiae quo laboriosam incidunt!”.',
      isRed: false,
    },
    {
      id: 5,
      name: 'Alexey Mikulskiy',
      location: 'Chernivtsi, Ukraine',
      image: './images/user-placeholder.png',
      rating: '4.3',
      text: '“Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab laboriosam dignissimos nostrum harum laborum quisquam totam accusantium, enim eum aperiam quidem labore reiciendis, facere possimus! Ipsam, consequuntur. At, dicta dolor.”.',
      isRed: false,
    },
    {
      id: 6,
      name: 'Bogdan Kushnir',
      location: 'Washington, USA',
      image: './images/user-placeholder.png',
      rating: '4.8',
      text: '“Lorem ipsum dolor sit amet, consectetur adipisicing elit. A aliquam eum totam voluptatum tenetur similique repudiandae illo reprehenderit eaque, deleniti quaerat obcaecati voluptas earum quod non dolore maxime neque vitae!”.',
      isRed: false,
    },
    {
      id: 7,
      name: 'Kim Young Jou',
      location: 'Seoul, South Korea',
      image: './images/user-placeholder.png',
      rating: '4.4',
      text: '“Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae modi sint soluta quia nam, dolorem dolores illum doloribus similique ab. Corporis, nihil ratione? Incidunt doloribus, quis quasi quos veniam aliquid.”.',
      isRed: false,
    },
    {
      id: 8,
      name: 'Kim Young Jou',
      location: 'Seoul, South Korea',
      image: './images/user-placeholder.png',
      rating: '4.6',
      text: '“Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur in dolores excepturi expedita quod. Amet magni beatae accusamus esse itaque aperiam qui, nam, labore illo quasi cum illum facere. Dolorum.”.',
      isRed: false,
    },
    {
      id: 9,
      name: 'Kim Young Jou',
      location: 'Seoul, South Korea',
      image: './images/user-placeholder.png',
      rating: '4.9',
      text: '“Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum quis laboriosam inventore sapiente, illo necessitatibus nostrum quidem! At sit, repellat explicabo unde quasi accusantium deserunt iste nesciunt dolorem exercitationem inventore!”.',
      isRed: false,
    },
    {
      id: 10,
      name: 'Kim Young Jou',
      location: 'Seoul, South Korea',
      image: './images/user-placeholder.png',
      rating: '4.5',
      text: '“Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos quis accusantium pariatur quasi quae impedit voluptatem velit modi corporis. Nulla reprehenderit blanditiis at architecto perspiciatis eos! Totam impedit autem repellat.”.',
      isRed: false,
    },
  ],
});
